### ISSUE TITLE
 this page is currently unavailable

### ISSUE THREAD

**Issue by gwt-ZJU** [lcpmgh/colors#1]
Hello, Showcase Cloud has an error: this page is currently unavailable

**Comment by lcpmgh** [comment]
Thank you for reporting the fault information. I checked the server and the cause of the fault was that the shiny-server.log file had recorded too many error logs, causing the file to become too large and fill up the disk space. This issue has now been resolved, and thank you again.

**Comment by lcpmgh** [comment]
> Hello, Showcase Cloud has an error: this page is currently unavailable

Thank you for reporting the fault information. I checked the server and the cause of the fault was that the shiny-server.log file had recorded too many error logs, causing the file to become too large and fill up the disk space. This issue has now been resolved, and thank you again.
